name = "transfer-management-system"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "transfer-management-db"
database_id = "1b58787a-5d84-49da-9e66-2e71132975cd"
